### ISSUE TITLE
Create tests to check navigation between screens

### ISSUE THREAD

**Issue by BratinaRok** [RedJocker/SimpleBankManagerTestCreation#18]

**Comment by RedJocker** [comment]
I already did some of that in this project on stage3

I'm just pressing back button on activity and expecting to find a new screen

this is the method to be used to press back button

https://github.com/RedJocker/SimpleBankManagerTestCreation/blob/75c771fbce5e7061b9514242746e7af9477edeb9/Simple%20Bank%20Manager/stage3/src/test/java/org/hyperskill/simplebankmanager/internals/AbstractUnitTest.kt#L122-L132

and here is the part consuming this code

https://github.com/RedJocker/SimpleBankManagerTestCreation/blob/75c771fbce5e7061b9514242746e7af9477edeb9/Simple%20Bank%20Manager/stage3/src/test/java/org/hyperskill/simplebankmanager/Stage3UnitTest.kt#L54-L65

But the consuming part could be improved, the try block is covering too much it can endup catching something unrelated and will be sending a message back to the user that is unrelated with his actual problem.

I will try to make something better.

**Comment by RedJocker** [comment]
this is a better pattern for the consumer code

```
       try {
                UserMenuScreen(this)
            } catch (error: AssertionError) {
                throw AssertionError("After clicking back button on ViewBalance screen UserMenu screen should be displayed")
            }.apply {
                userMenuViewBalanceButton.clickAndRun()
            }
```

here the try will only catching what happens on instantiation of the screen class and what happens in the apply won't, which is what we want.

send the description changes you made and I can do this update myself. I will make this test on test00 for stage3 4 and 5 which is already testing navigation. There are some other @test methods that are also using this. I will think if we keep with the updated pattern or if we just rely on test00 and assume the navigation is not a problem, I'm not sure yet.

**Comment by BratinaRok** [comment]
I made a pull request for a description fix. After this tests for back-click navigation, I will also need to update part of the description so that the user knows that also back navigation is tested.

**Comment by RedJocker** [comment]
@BratinaRok 
Check this last commit and close every issue that you think has been solved already.

Also check again the report to see if there are still any issues that were not fix

**Comment by BratinaRok** [comment]
@RedJocker I updated the description and opened new issues, most of which I already fixed. Please check.

**Comment by RedJocker** [comment]
No I prefer the older description, it is more precise on the requirement description, and first two stages don't need that requirement on description.

roll this back

**Comment by BratinaRok** [comment]
Did revert on desc for tests
