### ISSUE TITLE
 Provide required hints for users to complete the task more effectively.

### ISSUE THREAD

**Issue by BratinaRok** [RedJocker/SimpleBankManagerTestCreation#24]

**Comment by RedJocker** [comment]
please give a description on this issue so that we can better think about it

**Comment by RedJocker** [comment]
I still don't know what is this issue about, please give a description to it or close it if it is not an issue

**Comment by BratinaRok** [comment]
This is not even an issue. I was just thinking if some hints are to be added to each stage to help students easily pass stage with some help.
