### ISSUE TITLE
Add tests or explanations about passing data between fragments in the previous stage.

### ISSUE THREAD

**Issue by BratinaRok** [RedJocker/SimpleBankManagerTestCreation#26]

**Comment by BratinaRok** [comment]
I think that is already explained OK in project :
"It is also possible to pass a Bundle as the second argument of the navigate method to pass arguments to userMenuFragment, which you can later retrieve with arguments?.getString(...)"

**Comment by BratinaRok** [comment]
Or I can explain more in detail, but I think it should be topic job and not the project one.

**Comment by BratinaRok** [comment]
Maybe something like that, or this could be a hint?
When navigating from one fragment to another using the navigate method, you can pass data between the fragments by providing a Bundle as the second argument. In the Bundle, you can put any data you want to pass to the destination fragment, such as a string, integer, or even a custom object.

To retrieve the data in the destination fragment, you can use the arguments property, which returns the Bundle that was passed during navigation. You can then use the getString(), getInt(), or other methods of the Bundle class to extract the data from the Bundle.

**Comment by RedJocker** [comment]
Keep this on Objectives section:
https://github.com/RedJocker/SimpleBankManagerTestCreation/blob/75c771fbce5e7061b9514242746e7af9477edeb9/Simple%20Bank%20Manager/stage2/task.html#L17

You may add something more descriptive on Description section

**Comment by RedJocker** [comment]
last comment still valid

> Keep this on Objectives section:
> 
> https://github.com/RedJocker/SimpleBankManagerTestCreation/blob/75c771fbce5e7061b9514242746e7af9477edeb9/Simple%20Bank%20Manager/stage2/task.html#L17
> 
> You may add something more descriptive on Description section
